#!/bin/env bash
# source ~/.bashrc

sudo yum install zsh -y
sudo cat /etc/shells
sudo chsh -s $(which zsh) $(whoami)
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

HOME=~/SageMaker
cd $HOME 

alias simp='cd /home/ec2-user/SageMaker/sim_pro/afes-spark-healthcare-dsci-notebooks/FE_50109/'
cd /home/ec2-user/SageMaker/sim_pro/afes-spark-healthcare-dsci-notebooks/FE_50109alias ges='cd /home/ec2-user/SageMaker/GES/afes-spark-healthcare-dsci-notebooks/FE_50606/US_59310/repo/notebooks'
alias simp='cd /home/ec2-user/SageMaker/sim_pro/afes-spark-healthcare-dsci-notebooks/FE_50109/'
cd /home/ec2-user/SageMaker/sim_pro/afes-spark-healthcare-dsci-notebooks/FE_50109

## git env
git config --global user.email "saguinaga@deloitte.com"
git config --global user.name "Sal Aguinaga"


