verbose: 1

# Deloitte Pallium S3 stores
saS3Params: 
  bucket: afes-analytics-dev
  root_key: saguinaga/

# Database Credentials
postgres_db_host: afes-db-qa-1.cqzhzjcbqm18.us-east-1.rds.amazonaws.com
postgres_user_name: service_pharmatic
postgres_password: service_pharmatic
postgres_port: 5432
postgres_db_name: afes
neo4j_gdb: srp
neo4j_uri: bolt://localhost:7687
neo4j_username: neo4j
neo4j_password: P@llium123